version: '3.8'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    platform: linux/amd64
    
  patientsmicroservice:
    build:
      context: .
      dockerfile: PatientsMicroService/Dockerfile
    container_name: patientsmicroservice
    platform: linux/amd64
    ports:
      - "5001:80"
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=PatientsDb;User Id=sa;Password=Your_password123;Encrypt=True;TrustServerCertificate=True;
    depends_on:
      - sqlserver
      
  apigateway:
    build:
      context: .
      dockerfile: apiGateway/Dockerfile
    container_name: apigateway
    platform: linux/amd64
    ports:
      - "5000:80"
    depends_on:
      - patientsmicroservice